# ASSET_SHEET_FILENAME_WITHOUT_EXTENSION = "asset_sheet"
# ASSET_SHEET_FILENAME_WITH_EXTENSION = "asset_sheet.png"
# LATEST_ASSET_SHEET_NAME_STATE_KEY = "LATEST_ASSET_SHEET_NAME"

SCENE_IMAGE_FILENAME_PREFIX = "scene_image"
SCENE_VIDEO_FILENAME_PREFIX = "scene_video"
VIDEO_MIMETYPE = "video/mp4"
IMAGE_MIMETYPE = "image/png"
AUDIO_MIMETYPE = "audio/wav"